<?
$PERM["about"]["7"]="W";
$PERM["about"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["personal"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["7"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["7"]="W";
?>