<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Новинки");?><h1>Рекомендуемые товары</h1>
<?
	//include module
	\Bitrix\Main\Loader::includeModule("dw.deluxe");

	//vars
	$catalogIblockId = null;
	$arPriceCodes = array();

	//get template settings
	$arTemplateSettings = DwSettings::getInstance()->getCurrentSettings();
	if(!empty($arTemplateSettings)){
		$catalogIblockId = $arTemplateSettings["TEMPLATE_PRODUCT_IBLOCK_ID"];
		$arPriceCodes = explode(", ", $arTemplateSettings["TEMPLATE_PRICE_CODES"]);
	}
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:menu",
	"personal",
	Array(
		"ALLOW_MULTI_SELECT" => "N",
		"CHILD_MENU_TYPE" => "",
		"COMPONENT_TEMPLATE" => "personal",
		"DELAY" => "N",
		"MAX_LEVEL" => "1",
		"MENU_CACHE_GET_VARS" => array(),
		"MENU_CACHE_TIME" => "3600000",
		"MENU_CACHE_TYPE" => "A",
		"MENU_CACHE_USE_GROUPS" => "Y",
		"ROOT_MENU_TYPE" => "left2",
		"USE_EXT" => "N"
	)
);?><?$APPLICATION->IncludeComponent(
	"dresscode:simple.offers",
	"",
	Array(
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"DISABLE_SELECT_CATEGORY" => "N",
		"FILTER_PRICE_CODE" => array("BASE"),
		"HIDE_MEASURES" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "15",
		"IBLOCK_TYPE" => "catalog",
		"LAZY_LOAD_PICTURES" => "N",
		"PRICE_CODE" => array(),
		"PROPERTY_CODE" => array("COLOR","CML2_ARTICLE","OFFERS","VOTE_COUNT","SHOW_MENU","RATING","VOTE_SUM","BLOG_POST_ID","BLOG_COMMENTS_CNT","SIMILAR_PRODUCT","RELATED_PRODUCT","ATT_BRAND","ZOOM2","BATTERY_LIFE","SWITCH","GRAF_PROC","LENGTH_OF_CORD","DISPLAY","LOADING_LAUNDRY","FULL_HD_VIDEO_RECORD","INTERFACE","COMPRESSORS","Number_of_Outlets","MAX_RESOLUTION_VIDEO","MAX_BUS_FREQUENCY","MAX_RESOLUTION","FREEZER","POWER_SUB","POWER","HARD_DRIVE_SPACE","MEMORY","OS","ZOOM","PAPER_FEED","SUPPORTED_STANDARTS","VIDEO_FORMAT","SUPPORT_2SIM","MP3","ETHERNET_PORTS","MATRIX","CAMERA","PHOTOSENSITIVITY","DEFROST","SPEED_WIFI","SPIN_SPEED","PRINT_SPEED","SOCKET","IMAGE_STABILIZER","GSM","SIM","TYPE","MEMORY_CARD","TYPE_BODY","TYPE_MOUSE","TYPE_PRINT","CONNECTION","TYPE_OF_CONTROL","TYPE_DISPLAY","TYPE2","REFRESH_RATE","RANGE","AMOUNT_MEMORY","MEMORY_CAPACITY","VIDEO_BRAND","DIAGONAL","RESOLUTION","TOUCH","CORES","LINE_PROC","PROCESSOR","CLOCK_SPEED","TYPE_PROCESSOR","PROCESSOR_SPEED","HARD_DRIVE","HARD_DRIVE_TYPE","Number_of_memory_slots","MAXIMUM_MEMORY_FREQUENCY","TYPE_MEMORY","BLUETOOTH","FM","GPS","HDMI","SMART_TV","USB","WIFI","FLASH","ROTARY_DISPLAY","SUPPORT_3D","SUPPORT_3G","WITH_COOLER","FINGERPRINT","COLLECTION","TOTAL_OUTPUT_POWER","HTML","VID_ZASTECHKI","VID_SUMKI","VIDEO","PROFILE","VYSOTA_RUCHEK","GAS_CONTROL","WARRANTY","GRILL","MORE_PROPERTIES","GENRE","OTSEKOV","CONVECTION","INTAKE_POWER","NAZNAZHENIE","BULK","PODKLADKA","SURFACE_COATING","brand_tyres","SEASON","SEASONOST","DUST_COLLECTION","REF","COUNTRY_BRAND","DRYING","REMOVABLE_TOP_COVER","CONTROL","FINE_FILTER","FORM_FAKTOR","SKU_COLOR","USER_ID","DELIVERY","MARKER_PHOTO","NEW","DELIVERY_DESC","SALE","PICKUP","MARKER","POPULAR","WEIGHT","HEIGHT","DEPTH","WIDTH",""),
		"PROP_NAME" => "OFFERS",
		"PROP_VALUE" => "12"
	),
false,
Array(
	'ACTIVE_COMPONENT' => 'Y'
)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>